# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.11.3               # https://pyreadiness.org/3.9
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - pip:
    - rpaframework==26.1.0       # https://rpaframework.org/releasenotes.html
    - robocorp==0.10.1             # https://pypi.org/project/robocorp
    - robocorp-browser==2.1.0     # https://pypi.org/project/robocorp-browser
    - robocorp-excel==0.4.0       # https://pypi.org/project/robocorp-excel
    - robocorp-http==0.4.0       # https://pypi.org/project/robocorp-http
    - robotframework-browser==17.4.0
rccPostInstall:
    - rfbrowser init

